### ISSUE TITLE
blank page for a google account using one step authentication

### ISSUE THREAD

**Issue by aisbergde** [billyvg/pokemon-journal#22]
Windows download works fine and it is showing pokemons for a club account and for my google account: I have 2 step authentification and use an appliciation password. 

But there is another goolge account (of my daughter) using one-step authentifcation and for this account I get a blank screen after login. Login works because there was also an email informing that there was a new login into this account. Because this is a 1 step authentification there is no way to define an application password. So it looks like nothing in my environment but something depending on the account.

**Comment by aisbergde** [comment]
Changing from 1-step to 2-step-authentication doesn't solve the issue. Is there a way to create a log when logging in which could be helpful to find out the reason of the blank page?

**Comment by aisbergde** [comment]
Changing from 1-step to 2-step-authentication doesn't solve the issue. Is there a way to create a log when logging in which could be helpful to find out the reason of the blank page?

**Comment by mgedwards** [comment]
Created pull request #26 Update Package.json 
to update pogobuf module for login.
Should take care of this.

**Comment by billyvg** [comment]
Latest build should fix this https://github.com/billyvg/pokemon-journal/releases/tag/0.2.2

**Comment by aisbergde** [comment]
There is still a black screen for a specific google account
btw, also "pokemon-go-iv" doesn't work for this account.
Is there a way to create a log to analyze the reason for the issue?

**Comment by mgedwards** [comment]
There is already chrome dev tools. Right click the window and press inspect before attempting login. However, if you are having issues with a single account, it is most likely either an account setting or a ban. Are the security settings the same on both this account and a working account? Can you log into pokemon go? Etc.

**Comment by aisbergde** [comment]
I can open the chrome dev tools. But I don't find how to catch a possible error message which the server maybe will sent when login happens. The account works fine directly in the original pokemon go app. Because I get also an error for this account in "pokemon-go-iv" I will post the error messages I get using pokemon-go-iv in this project. I think the error reason is the same, something regarding to

> Error: Fetching RPC endpoint failed, received status code 51

**Comment by mgedwards** [comment]
The latest build should fix that error. Have you updated the packages and run npm update or npm install? Or downloaded the latest?

**Comment by aisbergde** [comment]
the latest build works fine on other accounts and solves issues on these accounts. but it doesn't solve the blank screen issue for this specific account.

**Comment by mgedwards** [comment]
Then there either must be something different about the settings of that account, or some sort of specific, one off problem with it. But if you open chrome dev tools with this app, it will output the error it gets in the console.
